spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.datasource.driverClassName=
spring.datasource.url=jdbc:postgresql://db:5432/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit

jwt.secret=${JWT_SECRET:your-256-bit-secret-key-for-jwt-token-generation-command-messenger-app}
jwt.expiration=${JWT_EXPIRATION:86400000} # 24 hours in milliseconds